import pandas as pd

# Define your topic and code
topic = "Customer Churn"
code = [
    "# Import necessary libraries",
    "import pandas as pd",
    "import matplotlib.pyplot as plt",
    "import seaborn as sns",
    "from sklearn.model_selection import train_test_split",
    "from sklearn.preprocessing import LabelEncoder",
    "from sklearn.ensemble import RandomForestClassifier",
    "from sklearn.metrics import classification_report, confusion_matrix, accuracy_score",
    "import joblib  # Optional: for saving model",
    "",
    "# Load CSV file",
    "file_path = 'customer_churn.csv'",
    "df = pd.read_csv(file_path)",
    "",
    "# Display first few rows",
    "print(\"First 5 rows:\")",
    "print(df.head())",
    "",
    "# Basic info",
    "print(\"\\nData Info:\")",
    "df.info()",
    "",
    "# Check for missing values",
    "print(\"\\nMissing values:\")",
    "print(df.isnull().sum())",
    "",
    "# Encode categorical variables",
    "le = LabelEncoder()",
    "categorical_cols = df.select_dtypes(include=['object']).columns",
    "for column in categorical_cols:",
    "    try:",
    "        df[column] = le.fit_transform(df[column].astype(str))",
    "    except Exception as e:",
    "        print(f\"Error encoding column {column}: {e}\")",
    "",
    "# Check if 'Churn' is present",
    "if 'Churn' in df.columns:",
    "    target_column = 'Churn'",
    "else:",
    "    raise ValueError(\"Target column 'Churn' not found. Please check your CSV.\")",
    "",
    "# Churn value distribution",
    "print(\"\\nChurn Value Counts:\")",
    "print(df[target_column].value_counts())",
    "",
    "# Correlation heatmap",
    "plt.figure(figsize=(10, 6))",
    "sns.heatmap(df.corr(), annot=True, cmap='coolwarm')",
    "plt.title('Feature Correlation Heatmap')",
    "plt.show()",
    "",
    "# Define features and target",
    "X = df.drop(target_column, axis=1)",
    "y = df[target_column]",
    "",
    "# Split data",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)",
    "",
    "# Train model",
    "model = RandomForestClassifier(n_estimators=100, random_state=42)",
    "model.fit(X_train, y_train)",
    "",
    "# Predict",
    "y_pred = model.predict(X_test)",
    "",
    "# Evaluate",
    "print(\"\\nAccuracy Score:\", accuracy_score(y_test, y_pred))",
    "print(\"\\nClassification Report:\\n\", classification_report(y_test, y_pred))",
    "",
    "# Confusion matrix",
    "conf_matrix = confusion_matrix(y_test, y_pred)",
    "sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues')",
    "plt.title('Confusion Matrix')",
    "plt.xlabel('Predicted')",
    "plt.ylabel('Actual')",
    "plt.show()",
    "",
    "# Feature importance",
    "feature_importances = pd.Series(model.feature_importances_, index=X.columns)",
    "feature_importances.nlargest(10).plot(kind='barh', color='teal')",
    "plt.title('Top 10 Feature Importances')",
    "plt.xlabel('Importance Score')",
    "plt.show()",
    "",
    "# Save model",
    "joblib.dump(model, 'customer_churn_model.pkl')",
    "print(\"\\nModel saved as 'customer_churn_model.pkl'\")"
]

# Create DataFrame with Topic, Line Number, and Code
df = pd.DataFrame({
    "Topic": [topic]*len(code),
    "Line Number": list(range(1, len(code) + 1)),
    "Code": code
})

# Save to CSV
df.to_csv("customer_churn_code.csv", index=False)
print("✅ Saved 'customer_churn_code.csv' successfully.")
